[event]
id = "user.create"
name = "User Created"
description = "New user was created in the system"
category = "auth"

[trigger]
action = "click"
element = "Add User button"

[[payload]]
name = "userId"
type = "string"
description = "Created user ID"

[[payload]]
name = "userName"
type = "string"
description = "Created user name"

[relations]
pages = ["users"]
entities = ["user"]

[implementation]
handler = "handleAddUser"
file = "core/app/src/pages/prototype/UsersPage.tsx"
line = 42
preview = "/prototype/users"
status = "implemented"
